//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASF_OneBot.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASF_OneBot.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 黑名单模式 的本地化字符串。
        /// </summary>
        internal static string BlackListMode {
            get {
                return ResourceManager.GetString("BlackListMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件当前工作模式: {0} 的本地化字符串。
        /// </summary>
        internal static string CurrentMode {
            get {
                return ResourceManager.GetString("CurrentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前为白名单模式, 并且Bot列表为空, 将不会监听任何Bot, 请参阅官方文档进行配置. 的本地化字符串。
        /// </summary>
        internal static string NoBotEffected {
            get {
                return ResourceManager.GetString("NoBotEffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂不支持此功能 的本地化字符串。
        /// </summary>
        internal static string NotSupportedYet {
            get {
                return ResourceManager.GetString("NotSupportedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正向/反向 WebSocket 均未运行, 请参阅官方文档进行配置. 的本地化字符串。
        /// </summary>
        internal static string NoWebSocketEnabled {
            get {
                return ResourceManager.GetString("NoWebSocketEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///            _____ ______           ____             ____        _   
        ///     /\    / ____|  ____|         / __ \           |  _ \      | |  
        ///    /  \  | (___ | |__    __  __ | |  | |_ __   ___| |_) | ___ | |_ 
        ///   / /\ \  \___ \|  __|   \ \/ / | |  | | &apos;_ \ / _ \  _ &lt; / _ \| __|
        ///  / ____ \ ____) | |       &gt;  &lt;  | |__| | | | |  __/ |_) | (_) | |_ 
        /// /_/    \_\_____/|_|      /_/\_\  \____/|_| |_|\___|____/ \___/ \__|
        ///                                                                    
        ///                     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PluginAbout {
            get {
                return ResourceManager.GetString("PluginAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 Chr_, 联系方式 chr@chrxw.com 的本地化字符串。
        /// </summary>
        internal static string PluginContact {
            get {
                return ResourceManager.GetString("PluginContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 版本 {1}.{2}.{3}.{4} 的本地化字符串。
        /// </summary>
        internal static string PluginVer {
            get {
                return ResourceManager.GetString("PluginVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件读取失败, 请参阅官方文档进行配置. 的本地化字符串。
        /// </summary>
        internal static string ReadConfigError {
            get {
                return ResourceManager.GetString("ReadConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反向 WebSocket 服务运行中, 访问地址: ws://{0}:{1} 的本地化字符串。
        /// </summary>
        internal static string ReWebSocketEnabled {
            get {
                return ResourceManager.GetString("ReWebSocketEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ======================================== 的本地化字符串。
        /// </summary>
        internal static string TextLine {
            get {
                return ResourceManager.GetString("TextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正向 WebSocket 服务运行中, 访问地址: ws://{0}:{1} 的本地化字符串。
        /// </summary>
        internal static string WebSocketEnabled {
            get {
                return ResourceManager.GetString("WebSocketEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 白名单模式 的本地化字符串。
        /// </summary>
        internal static string WhiteListMode {
            get {
                return ResourceManager.GetString("WhiteListMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端 {0} 鉴权失败, 请检查 AccessToken 配置是否正确. 的本地化字符串。
        /// </summary>
        internal static string WSClientAuthFailed {
            get {
                return ResourceManager.GetString("WSClientAuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端 {0} 连接成功, 当前连接数 {1} 的本地化字符串。
        /// </summary>
        internal static string WSClientConnected {
            get {
                return ResourceManager.GetString("WSClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端 {0} 连接出错, 当前连接数 {1} 的本地化字符串。
        /// </summary>
        internal static string WSClientConnectionFailed {
            get {
                return ResourceManager.GetString("WSClientConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端 {0} 断开连接, 当前连接数 {1} 的本地化字符串。
        /// </summary>
        internal static string WSClientDisconnected {
            get {
                return ResourceManager.GetString("WSClientDisconnected", resourceCulture);
            }
        }
    }
}
